// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzB7lXrYmcSCPwssx3a1tCj2bG_j4RaA',
    appId: '1:661304028062:web:07d329787d3925983f848f',
    messagingSenderId: '661304028062',
    projectId: 'amsp-4cca7',
    authDomain: 'amsp-4cca7.firebaseapp.com',
    storageBucket: 'amsp-4cca7.firebasestorage.app',
    measurementId: 'G-FBXK39FEQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANsCcTEvKAGA5QK1uJcifOiDS016Smi90',
    appId: '1:661304028062:android:7b54d3340c9f1e003f848f',
    messagingSenderId: '661304028062',
    projectId: 'amsp-4cca7',
    storageBucket: 'amsp-4cca7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YqvTfYlQ2vYcQimamrhqjLswUV0Q9zs',
    appId: '1:661304028062:ios:ba0f960c5b49c4f53f848f',
    messagingSenderId: '661304028062',
    projectId: 'amsp-4cca7',
    storageBucket: 'amsp-4cca7.firebasestorage.app',
    iosBundleId: 'com.example.amsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7YqvTfYlQ2vYcQimamrhqjLswUV0Q9zs',
    appId: '1:661304028062:ios:ba0f960c5b49c4f53f848f',
    messagingSenderId: '661304028062',
    projectId: 'amsp-4cca7',
    storageBucket: 'amsp-4cca7.firebasestorage.app',
    iosBundleId: 'com.example.amsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrzB7lXrYmcSCPwssx3a1tCj2bG_j4RaA',
    appId: '1:661304028062:web:d7179cbc562624c93f848f',
    messagingSenderId: '661304028062',
    projectId: 'amsp-4cca7',
    authDomain: 'amsp-4cca7.firebaseapp.com',
    storageBucket: 'amsp-4cca7.firebasestorage.app',
    measurementId: 'G-Y0K9BCFW0X',
  );
}
